language: java

dist: bionic

jdk: openjdk11

services:
  - xvfb

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - sudo apt-get update
  - sudo apt-get install -y openjfx
  - export DISPLAY=:99.0